using System;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
namespace Pellucid.Core.Api.Model
{
    public class Patient
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public string id { get; set; }
        public string name { get; set; }
        public string primary_phone_no { get; set; }
        public string age { get; set; }
        public string sex { get; set; }
        public DateTime? DOB { get; set; }
        [BsonExtraElements]
        public BsonDocument Addtional_information { get; set; }
        [BsonDateTimeOptions]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;

    }
}
